name: QCA-ALL

# CI计划
on:
  # 自动编译：当 Auto-Clean 运行完成后
  workflow_run:
    workflows: ["Auto-Clean"]
    types:
      - completed
  # 手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

# CI权限
permissions: write-all

# CI任务
jobs:
  config:
    name: ${{
      matrix.CONFIG }} / ${{ matrix.SOURCE }}
    strategy:
      fail-fast: false
      matrix:
        # 定义两个组合
        include:
          - CONFIG: IPQ60XX-WIFI-YES
            SOURCE: VIKINGYFY/immortalwrt
            BRANCH: main
          - CONFIG: IPQ60XX-WIFI-YES
            SOURCE: LiBwrt/openwrt-6.x
            BRANCH: kernel-6.12

    # 调用公用编译核心 WRT-CORE.yml
    uses: ./.github/workflows/WRT-CORE.yml
    with:
      # 编译配置
      WRT_CONFIG: ${{ matrix.CONFIG }}
      # 默认主题
      WRT_THEME: argon
      # 默认主机名
      WRT_NAME: AX1800
      # 默认 WIFI 名称
      WRT_SSID: AX1800
      # 默认 WIFI 密码
      WRT_WORD: 12345678
      # 默认地址
      WRT_IP: 192.168.3.18
      # 默认密码，仅作提示，修改无用
      WRT_PW: 无
      # 源码链接
      WRT_REPO: https://github.com/${{ matrix.SOURCE }}.git
      # 源码分支
      WRT_BRANCH: ${{ matrix.BRANCH }}
      # 源码名称
      WRT_SOURCE: ${{ matrix.SOURCE }}
      # 插件调整
      WRT_PACKAGE: ${{ inputs.PACKAGE }}
      # 仅输出配置文件
      WRT_TEST: ${{ inputs.TEST }}
